apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: img2webp-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |+
      rewrite ^/api/(.*)$ /$1 break;
spec:
  rules:
    - host: testtuchuang.top
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: img2webp-nginx
                port:
                  number: 80
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: img2webp-admin
                port:
                  number: 8861

---
apiVersion: v1
kind: Service
metadata:
  name: img2webp-nginx
spec:
  selector:
    app: img2webp-nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: img2webp-admin
spec:
  selector:
    app: img2webp-admin
  ports:
    - port: 8861
      targetPort: 8861
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: img2webp-nginx-config
data:
  defalut.conf: |+
    server {
        listen 80;
        server_name testimg2webp.top;
        index index.html;
        root /data;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: img2webp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img2webp-nginx
  template:
    metadata:
      name: img2webp-nginx
      labels:
        app: img2webp-nginx
    spec:
      containers:
        - name: img2webp-nginx
          image: registry.cn-hangzhou.aliyuncs.com/tanwuyang/img2webp-home:v2021_05_12_09_34
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: img2webp-nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: img2webp-admin
spec:
  selector:
    matchLabels:
      app: img2webp-admin
  template:
    metadata:
      name: img2webp-admin
      labels:
        app: img2webp-admin
    spec:
      containers:
        - name: img2webp
          image: registry.cn-hangzhou.aliyuncs.com/tanwuyang/img2webp-admin:v2021_05_12_09_17
          env:
            - name: REDIS_HOST
              value: base-service-endpoint
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8861
          volumeMounts:
            - mountPath: /img2webp/webp_zip
              name: web-static-file
      volumes:
        - name: web-static-file # 修改为 nas
          emptyDir: { }